### ISSUE TITLE
Credentials/Password

### ISSUE THREAD

**Issue by kndone** [devalexanderdaza/yowsapp-framework#12]
After registration I don't get a Password, I'm only getting something like this:

{"status":"ok","login":"521XXXXXXXXX","type":"new","edge_routing_info":"DBUIBg==","chat_dns_domain":"fb","security_code_set":false}

{
    "__version__": 1,
    "cc": "52",
    "client_static_keypair": "CDXXXXXXXXXXXpmY98uq3oi4rfnlksadnvo83438no3r00dGLTfNZRPbUFf4IIYrzGw==",
    "expid": "F/nfWz6pTvm+i798hiyhuMA==",
    "fdid": "8287hgi68-e025-40ea-aa4f-887yic496cd",
    "id": "b+dLdVUg3kugk7t8gBFlw/BRWmvo=",
    "mcc": "334",
    "mnc": "010",
    "phone": "521XXXXXXXXXX",
    "sim_mcc": "000",
    "sim_mnc": "000"
}
status: ok
edge_routing_info: DBUIBg==
login: 5214427972916
type: new

How can I use the framework whether I don't get a password? What can I do?

**Comment by Sharissa90** [comment]
with new protocol, yowup dont use password but client_static_keypair
open run.py and edit credentials like this
```
credentials = ("521XXXXXXXXXX", None)
```

**Comment by eduardocalazansjr** [comment]
Keep using config.py.

Put the value from "client_static_keypair" on the field "password", with the PR #13 it will just create an keypair from that value

**Comment by devalexanderdaza** [comment]
Solved!
