### ISSUE TITLE
No module named 'flask'

### ISSUE THREAD

**Issue by jesusvalverde** [devalexanderdaza/yowsapp-framework#14]
After a fresh and clean Ubuntu AWS server and perfome a simple of the book install

git clone https://github.com/devalexanderdaza/yowsapp-framework.git
cd yowsapp-framework
./yowsapp_installer.sh 
mv config_example.py config.py
sudo nano config.py 

** and fill the info

I do perfome a Small test and get 
Traceback (most recent call last):
  File "run.py", line 10, in <module>
    from app.layer import MacLayer
  File "/home/ubuntu/yowsapp-framework/app/layer.py", line 6, in <module>
    from app.utils import helper
  File "/home/ubuntu/yowsapp-framework/app/utils/helper.py", line 4, in <module>
    from flask import make_response
ModuleNotFoundError: No module named 'flask'

I have to add
pip3 install flask

and now everthing working fine.

**Comment by jesusvalverde** [comment]
This can be done 'cos the AssertionError is solved over yowsup.

https://github.com/devalexanderdaza/yowsapp-framework/issues/11

**Comment by devalexanderdaza** [comment]
Flask fixed on [this commit](https://github.com/devalexanderdaza/yowsapp-framework/commit/4f01557d0960a371fee1b276d7d8dc6f6675d339)
