### ISSUE TITLE
error registering number

### ISSUE THREAD

**Issue by gabrieru** [devalexanderdaza/yowsapp-framework#19]
Enter your country code: 51
Enter your mobile number without country code and + and 00: 99XXXXXX
Enter your MCC code <Lis of all MCC codes: https://www.mcc-mnc.com/>: 716
Enter your MNC code <Lis of all MCC codes: https://www.mcc-mnc.com/>: 15
Insert option number for code validation: 1. SMS - 2. VOICE: 1
Traceback (most recent call last):
  File "/usr/local/bin/yowsup-cli", line 4, in <module>
    __import__('pkg_resources').run_script('yowsup==3.2.3', 'yowsup-cli')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 739, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1486, in run_script
    raise ResolutionError("No script named %r" % script_name)
pkg_resources.ResolutionError: No script named 'yowsup-cli'
WhatsApp Code Validation
Insert the code: 
Enter a 6 numbers code:

**Comment by devalexanderdaza** [comment]
Close for duplicate [Here](https://github.com/devalexanderdaza/yowsapp-framework/issues/18)
