### ISSUE TITLE
credentials correctly within config.py

### ISSUE THREAD

**Issue by danielct59** [devalexanderdaza/yowsapp-framework#25]
good afternoon
could you give me an example of how to do as credentials correctly within config.py ??

**Comment by pablofuentes88** [comment]
Es fácil, aunque también caí en lo mismo, para resolverlo tienes que:
1) Ir a ~/.config/yowsup/<tu número de teléfono>
2) nano config.json
3) Copia el pass que está en client_static_keypair
4) Lo pegas en el archivo config.py del cual preguntas.

Listo!!

**Comment by danielct59** [comment]
![image](https://user-images.githubusercontent.com/35176091/58998692-7fe65d00-87d8-11e9-8442-c783b5726689.png)


============================================================

and so does not respond as messages ......

Please can anyone help me with this problem ??

**Comment by pablofuentes88** [comment]
If you want contact me fasted, write me in telegram https://t.me/PA3L0

[Whatsapp] Mac started

[Whatsapp] Current State: org.openwhatsapp.yowsup.event.network.connect
 * Serving Flask app "run" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
Sync contacts sucess: [573182217719]
 ->>>>>> MESSAGE RECEIVED!!!!!!
W 2019-06-06 01:54:07,216 yowsup.layers.protocol_media.layer - Unsupported mediatype: None, will send receipts
W 2019-06-06 01:54:07,216 yowsup.layers.protocol_media.protocolentities.message_media - media type: 'None' is not supported
 ->>>>>> MESSAGE RECEIVED!!!!!!
TEXT MESSAGE RECEIVED ->
Sync result:
Iq:
ID: 1
Type: result
from: 57315xxxxxx@s.whatsapp.net
Wait: 493669
Version: 1559770551317585
In Numbers:
Out Numbers: 57318xxxxxx
Invalid Numbers:

{'_class': 'receipt',
 '_from': 'status@broadcast',
 '_id': 'B371737930A9086851EAAF6D40E428B6',
 'tag': 'ack',
 'timestamp': None}

This work for me

**Comment by devalexanderdaza** [comment]
Solved
