### ISSUE TITLE
Whatsapp Bussines

### ISSUE THREAD

**Issue by pablofuentes88** [devalexanderdaza/yowsapp-framework#27]
The account of my bot appear like normal whatsapp, not a bussines account. Can I do some thing for that??

La cuenta asociada a mi número dejó de ser de Whatsapp Bussines y se convirtió en una cuenta normal del whatsapp, hay forma de configurar el bot para que aparezca como una cuenta empresarial?? gracias.

**Comment by MHilhorst** [comment]
Nope basically not, unless you register for real whatsapp api you need company with 50 employees.3

**Comment by devalexanderdaza** [comment]
> Nope basically not, unless you register for real whatsapp api you need company with 50 employees.3

Completely agree. It is important to keep in mind that this is a connection layer that does not use the official WhatsApp API and there are features that are still in testing, development and the route map of the developers.
