### ISSUE TITLE
Sync contacts error

### ISSUE THREAD

**Issue by paco020295** [devalexanderdaza/yowsapp-framework#32]
Hello.

I don't know what it really means. But when running start.sh, i'm getting some info and the last line says:
 Invalid Numbers: CONTACT_PHONE

I added my other phone number in config.py as CONTACT_PHONE. Can anyone point me in the right direction with this message?

**Comment by devalexanderdaza** [comment]
with pleasure! The correct way to incorporate telephone numbers into the Config file is as follows:

`contacts = {
    "+5731684XXXXX": "CONTACT NAME",
    "+5732033XXXXX": "ANOTHER CONTACT NAME",
    "+5735046XXXXX": "AND ANOTHER CONTACT NAME",
}`
