### ISSUE TITLE
Problen whit python

### ISSUE THREAD

**Issue by absolis** [devalexanderdaza/yowsapp-framework#35]
root@****:/opt/yowsapp-framework# ./start.sh
Traceback (most recent call last):
  File "run.py", line 10, in <module>
    from app.layer import MacLayer
  File "/opt/yowsapp-framework/app/layer.py", line 10, in <module>
    from modules import hihelp
  File "/opt/yowsapp-framework/modules/__init__.py", line 2, in <module>
    from modules import hiExample
  File "/opt/yowsapp-framework/modules/hiExample/__init__.py", line 25
    answer = "*Bot called mac* \nWhatsapp framework made in Python"+

any help?

**Comment by nurassyl** [comment]
vim modules/__init__.py
And add the code below

# Add here the modules you want to enable here                                                                                                                                         
#from modules import hiExample
from modules import hi_module

**Comment by nurassyl** [comment]
- Edit this file "modules/\_\_init\_\_.py"
And replace the content with this code below
`from modules import hi_module`

- And create the "modules/hi_module.py" file, (Written in README.md).

**Comment by devalexanderdaza** [comment]
Duplicated! Close now!
